const meals = [

  // ── ご飯もの ──────────────────────────────
  { id: "curry", name: "カレー", emoji: "🍛",
    type: "heavy", category: ["rice"], genre: "japanese",
    image: "images/curry.png",
    description: "スパイスが効いた定番の人気メニュー。家庭によって隠し味が異なり、チョコレートやリンゴを加えるのも人気。市販のルーから本格スパイスカレーまで幅広いアレンジが楽しめる。ご飯との相性は抜群で、福神漬けやらっきょうを添えると本格感がアップする。翌日に味がなじんでさらにおいしくなるのも魅力。",
    difficulty: 3, availability: 5,
    tags: ["ごちそう系"] },

  { id: "hayashi", name: "ハヤシライス", emoji: "🍛",
    type: "heavy", category: ["rice"], genre: "western",
    image: "images/hayashi.png",
    description: "デミグラスソースで煮込んだ牛肉がご飯に合う洋食の定番。じっくり煮込むほど旨みが深まり、トマトの酸味とコクのあるソースが絶妙なバランス。カレーと並ぶ家庭の定番で、玉ねぎをよく炒めることが美味しさの秘訣。仕上げに生クリームを加えるとよりリッチな味わいになる。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系"] },

  { id: "gyudon", name: "牛丼", emoji: "🥣",
    type: "normal", category: ["rice", "meat"], genre: "japanese",
    image: "images/gyudon.png",
    description: "甘辛い牛肉がご飯に染みる、手軽でうまい丼。玉ねぎと牛肉を割り下で煮込むだけで本格的な味に仕上がる。紅生姜や七味唐辛子をトッピングするのが定番で、温泉卵をのせると濃厚さがアップ。牛丼チェーンの味を家でも再現できる人気メニュー。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "oyakodon", name: "親子丼", emoji: "🥚",
    type: "normal", category: ["rice", "meat"], genre: "japanese",
    image: "images/oyakodon.png",
    description: "鶏肉と卵のふわとろコンビが絶品の丼もの。だしの効いた甘辛いタレで鶏肉を煮て、半熟卵でとじるのがポイント。名前の由来は親（鶏）と子（卵）を一緒に使うことから。シンプルな材料で短時間に作れるので忙しい日の定番メニューとしても重宝する。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "katsudon", name: "カツ丼", emoji: "🍱",
    type: "heavy", category: ["rice", "meat"], genre: "japanese",
    image: "images/katsudon.png",
    description: "サクサクのとんかつを卵でとじた、ボリューム満点の丼。揚げたてのとんかつを甘辛いだしで煮て、ふわふわの卵でとじるのが定番スタイル。試験や勝負の前に食べる縁起メニューとしても親しまれている。ソースカツ丼や味噌カツ丼など地域によってバリエーションも豊富。",
    difficulty: 3, availability: 5,
    tags: ["ごちそう系", "揚げ物"] },

  { id: "chukadan", name: "中華丼", emoji: "🥡",
    type: "heavy", category: ["rice"], genre: "chinese",
    image: "images/chukadan.png",
    description: "八宝菜風のあんがご飯に絡む、ボリューム満点の中華丼。豚肉・エビ・野菜・うずらの卵などさまざまな具材が入った贅沢な一品。とろみのあるあんがご飯によく絡み、食べ応え十分。家庭では冷蔵庫の残り野菜を活用しやすく、アレンジしやすいメニュー。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "butadon", name: "豚丼", emoji: "🥣",
    type: "heavy", category: ["rice", "meat"], genre: "japanese",
    image: "images/butadon.png",
    description: "甘辛いタレで焼いた豚肉がご飯に乗った北海道発祥のメニュー。帯広が発祥とされ、豚肉を香ばしく焼き上げてタレを絡めるシンプルな調理法が魅力。牛丼に比べてリーズナブルで食べ応えがあり、ご飯との相性も抜群。ネギや温泉卵をトッピングするとさらにおいしくなる。",
    difficulty: 2, availability: 5,
    tags: ["ごちそう系"] },

  { id: "omurice", name: "オムライス", emoji: "🍳",
    type: "normal", category: ["rice"], genre: "western",
    image: "images/omurice.png",
    description: "ケチャップライスをふわふわ卵で包んだ洋食の定番。卵のふわとろ感が決め手で、家庭によってデミグラスソースやホワイトソースをかけるアレンジも人気。子どもから大人まで幅広く愛される一品で、ケチャップで絵を描く楽しみ方も定番。喫茶店のメニューとしても長年愛されている。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系"] },

  { id: "friedrice", name: "チャーハン", emoji: "🍚",
    type: "normal", category: ["rice"], genre: "chinese",
    image: "images/friedrice.png",
    description: "パラパラに炒めたご飯が香ばしい中華の定番。強火で一気に炒めることでパラパラ食感に仕上がる。具材は卵・ねぎ・チャーシューが定番だが、冷蔵庫の残り物でアレンジしやすい。醤油や塩など味付けのバリエーションも豊富で、ラーメンの締めにも人気のメニュー。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "tenshinhan", name: "天津飯", emoji: "🍳",
    type: "normal", category: ["rice"], genre: "chinese",
    image: "images/tenshinhan.png",
    description: "ふわふわのかに玉あんかけがご飯に乗った中華の定番。卵をふんわり半熟に仕上げてご飯に乗せ、甘酢あんまたは醤油あんをかけるスタイルが一般的。日本発祥の中華料理とされており、あんのとろみがご飯によく絡む。シンプルながら満足感が高く、中華料理店の人気メニュー。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "doria", name: "ドリア", emoji: "🍚",
    type: "normal", category: ["rice", "flour"], genre: "western",
    image: "images/doria.png",
    description: "クリームソースとチーズをかけてオーブンで焼いた洋食。バターライスの上にホワイトソースとチーズをたっぷりのせてこんがり焼き上げる。横浜のホテルニューグランドで生まれたとされる日本発祥の洋食メニュー。熱々のうちにスプーンですくって食べるのが定番スタイル。",
    difficulty: 4, availability: 3,
    tags: ["ごちそう系"] },

  { id: "bibimbap", name: "ビビンバ", emoji: "🥗",
    type: "normal", category: ["rice"], genre: "other",
    image: "images/bibimbap.png",
    description: "ナムルや肉を混ぜて食べる韓国の定番ご飯。ほうれん草・もやし・にんじんなどのナムルと甘辛い肉をご飯に乗せ、コチュジャンで混ぜて食べる。石焼きビビンバはおこげが香ばしく格別の美味しさ。野菜をたっぷり摂れてバランスが良く、ヘルシーな韓国料理として人気。",
    difficulty: 3, availability: 4,
    tags: ["辛い"] },

  { id: "tacorice", name: "タコライス", emoji: "🌮",
    type: "normal", category: ["rice"], genre: "other",
    image: "images/tacorice.png",
    description: "タコスの具材をご飯に乗せた沖縄発のB級グルメ。ひき肉・レタス・トマト・チーズをご飯に乗せてサルサソースをかけるスタイルが定番。沖縄の米軍基地周辺で生まれたとされるご当地グルメで、今では全国的に人気。手軽に作れてボリュームもあり、若い世代にも人気のメニュー。",
    difficulty: 2, availability: 4,
    tags: ["ジャンク系"] },

  { id: "loco", name: "ロコモコ丼", emoji: "🍳",
    type: "heavy", category: ["rice", "meat"], genre: "other",
    image: "images/loco.png",
    description: "ハンバーグと目玉焼きをグレービーソースで絡めたハワイ料理。ご飯の上にハンバーグ・目玉焼きを乗せ、濃厚なグレービーソースをかけて食べる。ハワイのローカルフードとして生まれ、日本でも定番化した人気メニュー。ボリューム満点でスタミナをつけたい日にぴったり。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系"] },

  { id: "gapao", name: "ガパオライス", emoji: "🌿",
    type: "normal", category: ["rice"], genre: "other",
    image: "images/gapao.png",
    description: "バジルと鶏肉の炒め物を乗せたタイ料理。鶏ひき肉をナンプラーやオイスターソースで炒め、ホーリーバジルを加えるのが本場スタイル。目玉焼きをのせて崩しながら食べるのが定番で、エスニックな香りが食欲をそそる。日本でもエスニック料理として広く親しまれている。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "kaisen", name: "海鮮丼", emoji: "🐟",
    type: "normal", category: ["rice", "fish"], genre: "japanese",
    image: "images/kaisen.png",
    description: "新鮮な魚介がたっぷり乗った贅沢な丼。まぐろ・サーモン・いくらなど旬の魚介をご飯に乗せ、醤油やわさびで味わう。新鮮な素材の美味しさをシンプルに楽しめる一品で、市場や港町の食堂で食べるのが格別。家庭でも刺身パックを使えば手軽に再現できる。",
    difficulty: 2, availability: 4,
    tags: ["ごちそう系"] },

  { id: "sushi", name: "寿司", emoji: "🍣",
    type: "heavy", category: ["rice", "fish"], genre: "japanese",
    image: "images/sushi.png",
    description: "新鮮なネタとシャリの組み合わせが最高の日本の伝統料理。江戸時代から続く日本を代表する食文化で、回転寿司から高級店まで幅広いスタイルがある。季節によって旬のネタが変わるのも楽しみのひとつ。手巻き寿司なら家庭でも気軽に楽しめ、みんなで囲む食卓に最適。",
    difficulty: 4, availability: 4,
    tags: ["ごちそう系"] },

  { id: "unaju", name: "うな重", emoji: "🐡",
    type: "heavy", category: ["rice", "fish"], genre: "japanese",
    image: "images/unaju.png",
    description: "タレをたっぷり絡めた鰻がご飯に乗った特別感のある一品。蒸してから焼く関東風と蒸さずに焼く関西風でスタイルが異なる。夏の土用の丑の日に食べる習慣が有名で、スタミナ補給にも最適とされる。濃厚なタレがご飯に染みてたまらない、日本のご馳走のひとつ。",
    difficulty: 4, availability: 3,
    tags: ["ごちそう系"] },

  { id: "tkg", name: "卵かけご飯", emoji: "🥚",
    type: "light", category: ["rice", "side"], genre: "japanese",
    image: "images/tkg.png",
    description: "シンプルだけど奥深い、日本人のソウルフード。炊きたてのご飯に生卵を割り入れ、醤油をかけるだけのシンプルな一品。卵の鮮度がそのまま味に直結するので、新鮮な卵を使うのが美味しさの秘訣。だし醤油やめんつゆを使うとさらに深みが出る。日本独自の食文化として海外でも注目されている。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "onigiri", name: "おにぎり", emoji: "🍙",
    type: "light", category: ["rice", "side"], genre: "japanese",
    image: "images/onigiri.png",
    description: "シンプルだけど飽きない日本の定番。梅・鮭・昆布など定番の具材から唐揚げやツナマヨなど人気の具材まで種類が豊富。塩加減と握り具合が美味しさの決め手で、海苔で包むとさらに風味がアップ。お弁当や遠足の定番として、日本人の食生活に欠かせない存在。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "ochazuke", name: "お茶漬け", emoji: "🍵",
    type: "light", category: ["rice", "side"], genre: "japanese",
    image: "images/ochazuke.png",
    description: "だし茶をかけてさらっと食べる和のファストフード。梅干し・鮭・明太子など好みの具材をご飯に乗せ、熱いお茶やだし汁をかけて食べる。食欲がない日や食べ過ぎた後の締めにもぴったり。お茶の香りとだしの風味がご飯に染みてほっとする味わい。永谷園のお茶漬けの素は日本の家庭に欠かせない定番品。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "tendon", name: "天丼", emoji: "🍤",
    type: "heavy", category: ["rice"], genre: "japanese",
    image: "images/tendon.png",
    description: "サクサクの天ぷらにタレが絡む、ご飯が進む丼もの。えび・いか・野菜などの天ぷらを甘辛いタレに絡めてご飯に乗せる。天ぷらの衣にタレが染みたところが絶品で、熱々のうちに食べるのが一番。江戸時代から続く日本の定番丼で、今でも天丼専門店が全国に多数ある。",
    difficulty: 4, availability: 4,
    tags: ["ごちそう系", "揚げ物"] },

  // ── 麺類 ──────────────────────────────────
  { id: "ramen", name: "ラーメン", emoji: "🍜",
    type: "heavy", category: ["noodle"], genre: "chinese",
    image: "images/ramen.png",
    description: "濃厚なスープと麺が絡む、日本の国民食。醤油・塩・味噌・豚骨など地域によってスープのスタイルが異なり、全国各地にご当地ラーメンが存在する。トッピングのチャーシューやメンマ・煮卵も楽しみのひとつ。専門店の味を自宅で再現しようとするラーメンマニアも多い奥深い一杯。",
    difficulty: 2, availability: 5,
    tags: ["ごちそう系"] },

  { id: "udon", name: "うどん", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "japanese",
    image: "images/udon.png",
    description: "もちもちの麺が体に優しい定番麺。讃岐うどんに代表されるコシの強い麺から、関西風のやわらかい麺までスタイルが幅広い。かけ・ざる・釜玉・カレーうどんなどアレンジが豊富で飽きない。シンプルなだしの旨みが麺に絡み、体調が優れない日にもすっと食べられる。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "soba", name: "そば", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "japanese",
    image: "images/soba.png",
    description: "風味豊かな蕎麦の香りがたまらない日本の伝統麺。新そばの季節には香りが一層豊かになる。ざるそば・かけそば・天ざるなど食べ方も多彩で、年越しそばとして大晦日に食べる習慣も根付いている。つゆにつけて食べる際は、麺の半分だけつけると香りを楽しめると言われている。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "hiyashi", name: "冷やし中華", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "chinese",
    image: "images/hiyashi.png",
    description: "暑い日に食べたくなる夏の定番麺。ハム・きゅうり・錦糸卵・トマトなどの具材を彩りよく並べ、酸味のあるタレをかけて食べる。「冷やし中華はじめました」の張り紙は夏の風物詩として親しまれている。ごまだれバージョンも人気で、暑い夏に食欲を取り戻してくれる一杯。",
    difficulty: 2, availability: 4,
    tags: [] },

  { id: "tsukemen", name: "つけ麺", emoji: "🍜",
    type: "heavy", category: ["noodle"], genre: "chinese",
    image: "images/tsukemen.png",
    description: "濃厚なつけ汁に麺をくぐらせて食べる、ラーメンの進化系。麺とスープを別々に楽しむスタイルで、最後に割りスープを加えてスープまで飲み干すのが定番。麺の量が多めでも食べやすく、ボリュームを重視する人に人気。魚介系と豚骨を合わせた濃厚スープが主流で、専門店も全国に多数ある。",
    difficulty: 2, availability: 4,
    tags: ["ごちそう系"] },

  { id: "yakisoba", name: "焼きそば", emoji: "🍜",
    type: "normal", category: ["noodle"], genre: "japanese",
    image: "images/yakisoba.png",
    description: "ソース香る炒め麺。豚肉・キャベツ・もやしなどを一緒に炒めてウスターソースで味付けするのが定番スタイル。お祭りの屋台や文化祭の定番として親しまれており、青のりと紅生姜のトッピングが欠かせない。塩焼きそばや醤油ベースなどアレンジも豊富で、家庭でも手軽に作れる。",
    difficulty: 2, availability: 5,
    tags: ["ジャンク系"] },

  { id: "pasta", name: "パスタ", emoji: "🍝",
    type: "normal", category: ["noodle"], genre: "western",
    image: "images/pasta.png",
    description: "ソース次第で無限のアレンジが楽しめるイタリアの定番。ミートソース・カルボナーラ・ペペロンチーノなど定番から、和風・明太子・たらこなど日本独自のアレンジまで幅広い。麺の太さや形によって合うソースが異なり、奥が深い料理のひとつ。茹で時間とアルデンテの加減がおいしさの決め手。",
    difficulty: 3, availability: 5,
    tags: [] },

  { id: "tantanmen", name: "担々麺", emoji: "🍜",
    type: "heavy", category: ["noodle"], genre: "chinese",
    image: "images/tantanmen.png",
    description: "ピリ辛のごまスープが濃厚でクセになる中華麺。中国・四川省発祥のスパイシーな麺料理で、日本では芝麻醤（ねりごま）を使った濃厚なスープが主流。花椒（ホアジャオ）のしびれる辛さが特徴で、辛さの中にごまの甘みと旨みが広がる。辛いものが好きな人にはたまらない一杯。",
    difficulty: 3, availability: 4,
    tags: ["辛い", "ごちそう系"] },

  { id: "chanpon", name: "ちゃんぽん", emoji: "🍜",
    type: "heavy", category: ["noodle"], genre: "chinese",
    image: "images/chanpon.png",
    description: "野菜・肉・魚介がたっぷり入った長崎発のボリューム麺。豚肉・エビ・イカ・かまぼこ・キャベツ・もやしなど具材が豊富で、一杯で栄養バランスが取れる。豚骨と鶏ガラをベースにした白濁スープが特徴で、麺は専用の太麺を使う。長崎を代表するご当地グルメとして全国的に人気。",
    difficulty: 3, availability: 4,
    tags: ["野菜多め"] },

  { id: "reimen", name: "冷麺", emoji: "🍜",
    type: "normal", category: ["noodle"], genre: "other",
    image: "images/reimen.png",
    description: "コシのある麺を冷たいスープで食べる韓国料理。牛骨や鶏ガラベースの冷たいスープに細くコシのある麺を入れ、キムチ・きゅうり・ゆで卵などをトッピングする。平壌冷麺と咸興冷麺の2種類が有名で、スープの味わいが異なる。夏に食べると体がすっきりする爽やかな一品。",
    difficulty: 2, availability: 4,
    tags: ["辛い"] },

  { id: "somen", name: "素麺", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "japanese",
    image: "images/somen.png",
    description: "夏の暑い日にするっと食べられる細麺。氷水で締めた麺をめんつゆにつけてすするシンプルな食べ方が定番。揖保乃糸に代表される高級素麺は贈り物としても人気。薬味にねぎ・みょうが・生姜を添えると風味がアップする。食欲がない暑い夏でもするっと食べられる日本の夏の定番。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "pho", name: "フォー", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "other",
    image: "images/pho.png",
    description: "澄んだスープと米粉麺が体に優しいベトナムの定番麺。牛骨や鶏ガラを長時間煮出した清澄なスープに米粉の平打ち麺を合わせる。ライム・もやし・パクチー・バジルなどをトッピングして自分好みにカスタマイズするのが楽しい。ヘルシーで消化が良く、体に優しい一杯として人気。",
    difficulty: 3, availability: 3,
    tags: [] },
    
    // ── 肉料理 ──────────────────────────────────
  { id: "yakiniku", name: "焼肉", emoji: "🥩",
    type: "heavy", category: ["meat"], genre: "other",
    image: "images/yakiniku.png",
    description: "自分で焼くのが楽しい、みんな大好きな肉料理。カルビ・ロース・ホルモンなど部位ごとに異なる味わいが楽しめる。タレや塩など味付けを変えながら食べるのが定番スタイル。みんなで囲んでわいわい食べる楽しさがあり、特別な日のごちそうとして人気が高い。",
    difficulty: 2, availability: 2,
    tags: ["ごちそう系"] },

  { id: "steak", name: "ステーキ", emoji: "🥩",
    type: "heavy", category: ["meat"], genre: "western",
    image: "images/steak.png",
    description: "豪快に焼いた厚切り肉。焼き加減はレア・ミディアム・ウェルダンから好みで選べる。良質な牛肉の旨みを最大限に引き出すシンプルな料理で、塩・胡椒だけで十分な美味しさ。付け合わせのポテトやサラダとのバランスも楽しみのひとつで、特別な日に食べたくなる一品。",
    difficulty: 3, availability: 3,
    tags: ["ごちそう系"] },

  { id: "hamburg", name: "ハンバーグ", emoji: "🍖",
    type: "heavy", category: ["meat"], genre: "western",
    image: "images/hamburg.png",
    description: "ジューシーな肉汁があふれる洋食の定番。牛豚合い挽き肉に玉ねぎ・パン粉・卵を混ぜて成形し、フライパンで焼き上げる。デミグラスソース・和風おろし・トマトソースなどソースのバリエーションが豊富。ふっくらジューシーに仕上げるコツは、焼く前に中央をくぼませること。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系"] },

  { id: "karaage", name: "唐揚げ", emoji: "🍗",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/karaage.png",
    description: "外はカリッ、中はジューシー。揚げ物の王様。鶏もも肉を醤油・にんにく・生姜ベースのタレに漬け込んで揚げるのが定番。レモンを絞ってさっぱり食べるのが好きな人と、そのまま食べるのが好きな人で派閥が分かれる定番の議論も有名。お弁当・居酒屋・家庭料理と幅広いシーンで愛される一品。",
    difficulty: 3, availability: 5,
    tags: ["揚げ物", "おつまみ系"] },

  { id: "tonkatsu", name: "とんかつ", emoji: "🍖",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/tonkatsu.png",
    description: "サクサクの衣に包まれたジューシーな豚肉。ロースとヒレで味わいが異なり、ロースは脂の甘み、ヒレはあっさりとした赤身が楽しめる。千切りキャベツとソースの組み合わせが定番で、ご飯・味噌汁との定食スタイルが最高。揚げたての衣のサクサク感が最大の魅力。",
    difficulty: 3, availability: 5,
    tags: ["揚げ物", "ごちそう系"] },

  { id: "chickenkatsu", name: "チキンカツ", emoji: "🍗",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/chickenkatsu.png",
    description: "鶏肉をサクサクに揚げたカツ。とんかつに比べてあっさりしていて食べやすく、ボリュームも十分。タルタルソースや和風おろしとの相性が良く、ご飯が進む一品。鶏むね肉を使うとよりヘルシーに仕上がり、ダイエット中でも満足感が得られると人気。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物"] },

  { id: "chikinnamban", name: "チキン南蛮", emoji: "🍗",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/chikinnamban.png",
    description: "甘酢とタルタルソースが絡む宮崎発の鶏肉料理。揚げた鶏肉を甘酢に絡め、手作りタルタルソースをたっぷりかけるのが定番スタイル。宮崎県延岡市発祥のご当地料理で、今では全国の定食屋や弁当でも定番メニューに。タルタルソースのまろやかさと甘酢の酸味が絶妙にマッチする。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物", "ごちそう系"] },

  { id: "yurinchi", name: "油淋鶏", emoji: "🍗",
    type: "heavy", category: ["meat"], genre: "chinese",
    image: "images/yurinchi.png",
    description: "揚げた鶏肉にネギソースをかけた中華料理。鶏もも肉をカリッと揚げて、ねぎ・生姜・にんにくを使った甘酸っぱいタレをかける。パリパリの皮とジューシーな肉、香味ソースの組み合わせがクセになる。中華料理店の定番メニューで、ご飯との相性も抜群。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物"] },

  { id: "shogayaki", name: "豚の生姜焼き", emoji: "🥩",
    type: "normal", category: ["meat"], genre: "japanese",
    image: "images/shogayaki.png",
    description: "甘辛い生姜ダレで炒めた豚肉。定食の王道メニューとして全国の食堂や定食屋で親しまれている。生姜の風味がアクセントになり、豚肉の旨みを引き立てる。千切りキャベツと一緒に食べるのが定番スタイルで、ご飯との相性は言うまでもなく抜群。疲れた日に食べたくなる安心感のある一品。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "yakitori", name: "焼き鳥", emoji: "🍢",
    type: "normal", category: ["meat"], genre: "japanese",
    image: "images/yakitori.png",
    description: "タレや塩でシンプルに焼いた鶏肉串。もも・ねぎま・つくね・ぼんじりなど部位や種類が豊富で、食べ比べる楽しさがある。炭火で焼いた香ばしさは格別で、居酒屋の定番メニューとして親しまれている。タレか塩かの選択は焼き鳥好きにとって重要な問題。",
    difficulty: 3, availability: 5,
    tags: ["おつまみ系"] },

  { id: "roastbeef", name: "ローストビーフ", emoji: "🥩",
    type: "heavy", category: ["meat"], genre: "western",
    image: "images/roastbeef.png",
    description: "じっくり焼いた牛肉の塊。オーブンで低温調理することでしっとりやわらかく仕上がり、中心部がほんのりピンク色になるのが理想的な焼き加減。薄くスライスしてソースをかけて食べるスタイルが定番。おもてなし料理や特別な日のごちそうとして喜ばれる、見た目も華やかな一品。",
    difficulty: 4, availability: 3,
    tags: ["ごちそう系"] },

  { id: "hoikoro", name: "回鍋肉", emoji: "🥬",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/hoikoro.png",
    description: "キャベツと豚肉を甜麺醤で炒めた中華の定番おかず。甜麺醤・豆板醤・にんにく・生姜の組み合わせが深い味わいを生み出す。キャベツとピーマンのシャキシャキ感と豚肉の旨みが絡み合い、ご飯が止まらなくなる一品。四川料理のひとつで、日本でも家庭料理として広く親しまれている。",
    difficulty: 3, availability: 4,
    tags: ["野菜多め"] },

  { id: "subuta", name: "酢豚", emoji: "🍖",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/subuta.png",
    description: "揚げた豚肉を甘酢あんで絡めた中華の人気料理。豚肉を揚げてから玉ねぎ・ピーマン・にんじんと一緒に甘酢あんで炒め合わせる。パイナップルを入れるかどうかで意見が分かれる定番の論争も有名。揚げた豚肉の食感と甘酸っぱいあんのバランスが絶妙な中華の人気メニュー。",
    difficulty: 4, availability: 4,
    tags: ["揚げ物"] },

  { id: "chinjao", name: "青椒肉絲", emoji: "🫑",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/chinjao.png",
    description: "ピーマンと牛肉の細切り炒め。シャキシャキのピーマンと牛肉を細切りにして強火でさっと炒めるのがポイント。オイスターソースと醤油ベースのシンプルな味付けが素材の旨みを引き立てる。ピーマンが苦手な人でも食べやすく、ご飯のおかずとして定番の中華料理。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "mapo", name: "麻婆豆腐", emoji: "🌶️",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/mapo.png",
    description: "ピリ辛のひき肉あんが豆腐に絡む中華の定番。豆板醤・甜麺醤・花椒を使った本格的な味付けがクセになる四川料理。辛さの中にしびれる感覚が特徴で、辛いもの好きにはたまらない。豆腐が柔らかくあんをたっぷり吸い込んでご飯が進む。辛さを調節することで子どもから大人まで楽しめる。",
    difficulty: 3, availability: 5,
    tags: ["辛い"] },

  { id: "rebanira", name: "レバニラ炒め", emoji: "🥬",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/rebanira.png",
    description: "レバーとニラを炒めたスタミナ満点の中華おかず。豚レバーの独特の旨みとニラの香りが組み合わさったパワフルな一品。レバーを牛乳に浸してから使うと臭みが抑えられる。鉄分・ビタミンが豊富で疲労回復にも効果的とされており、スタミナをつけたい日にぴったりのメニュー。",
    difficulty: 2, availability: 4,
    tags: [] },

  { id: "gyoza", name: "餃子", emoji: "🥟",
    type: "normal", category: ["meat", "side"], genre: "chinese",
    image: "images/gyoza.png",
    description: "パリッと焼けた皮とジューシーな餡が最高。豚ひき肉・キャベツ・ニラを合わせた餡を薄い皮で包み、フライパンでこんがり焼き上げる。酢醤油やラー油で食べるのが定番で、ビールとの相性も抜群。宇都宮や浜松は餃子の町として有名で、地域ごとに個性的なスタイルがある。",
    difficulty: 3, availability: 5,
    tags: ["おつまみ系"] },

  { id: "kakuni", name: "豚の角煮", emoji: "🍖",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/kakuni.png",
    description: "じっくり煮込んだ豚バラ肉がとろとろに仕上がる。醤油・みりん・砂糖・酒を合わせたタレで長時間煮込むことで、箸で切れるほどやわらかくなる。沖縄のラフテーも同じ系統の料理で、地域ごとに味付けが異なる。手間はかかるが、完成したときの満足感はひとしおの特別なおかず。",
    difficulty: 4, availability: 4,
    tags: ["ごちそう系"] },

  { id: "nikujaga", name: "肉じゃが", emoji: "🥔",
    type: "normal", category: ["meat"], genre: "japanese",
    image: "images/nikujaga.png",
    description: "じゃがいもと肉を甘辛く煮た和食の定番おかず。牛肉または豚肉とじゃがいも・玉ねぎ・にんじんを甘辛い醤油だれで煮込む。日本の家庭料理を代表する「おふくろの味」として長年愛されている。じゃがいもに味が染みたころが食べごろで、翌日に温め直すとさらに美味しくなる。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "rollcabbage", name: "ロールキャベツ", emoji: "🥬",
    type: "normal", category: ["meat"], genre: "western",
    image: "images/rollcabbage.png",
    description: "キャベツでひき肉を包んでじっくり煮込んだ洋食おかず。牛豚合い挽き肉を柔らかく茹でたキャベツで丁寧に包み、コンソメスープでじっくり煮込む。トマト味やクリーム味など仕上げのバリエーションも楽しめる。手間がかかる分、完成したときの達成感と美味しさは格別な家庭料理。",
    difficulty: 4, availability: 4,
    tags: ["野菜多め"] },

  { id: "croquette", name: "コロッケ", emoji: "🥔",
    type: "normal", category: ["meat", "side"], genre: "japanese",
    image: "images/croquette.png",
    description: "じゃがいもとひき肉をサクサクに揚げた定番惣菜。マッシュしたじゃがいもとひき肉・玉ねぎを合わせて成形し、パン粉をつけて揚げる。ソースをかけてそのまま食べるほか、コロッケパンにして食べるのも人気。肉屋さんの揚げたてコロッケは格別で、日本の惣菜文化を代表する一品。",
    difficulty: 3, availability: 5,
    tags: ["揚げ物"] },

  { id: "menchikatsu", name: "メンチカツ", emoji: "🍖",
    type: "normal", category: ["meat", "side"], genre: "japanese",
    image: "images/menchikatsu.png",
    description: "ひき肉をサクサクの衣で揚げたボリューム感のある惣菜。牛豚合い挽き肉に玉ねぎを混ぜて成形し、パン粉をつけて揚げる。ハンバーグを揚げたような食べ応えで、ソースをかけてご飯と一緒に食べるのが定番。肉屋さんやスーパーの惣菜コーナーでも人気の定番揚げ物。",
    difficulty: 3, availability: 5,
    tags: ["揚げ物"] },

  { id: "sukiyaki", name: "すき焼き", emoji: "🍲",
    type: "heavy", category: ["meat", "nabe"], genre: "japanese",
    image: "images/sukiyaki.png",
    description: "甘辛いタレで牛肉や野菜を煮た日本の特別なごちそう鍋。割り下で牛肉・豆腐・白菜・ねぎ・春菊・しらたきを煮て、溶き卵につけて食べるのが定番。関東風は割り下で煮るスタイル、関西風は肉を焼いてから砂糖・醤油を加えるスタイルで異なる。特別な日や冬の寒い夜に食べたくなる贅沢鍋。",
    difficulty: 3, availability: 3,
    tags: ["ごちそう系"] },

  // ── 魚料理 ──────────────────────────────────
  { id: "yakizakana", name: "焼魚", emoji: "🐟",
    type: "light", category: ["fish"], genre: "japanese",
    image: "images/yakizakana.png",
    description: "塩焼きや醤油焼きでシンプルに楽しむ和食の定番。さば・さんま・鮭など季節の魚を塩焼きにするだけで素材の旨みが引き立つ。大根おろしと醤油を添えて食べるのが定番スタイルで、ご飯との相性は抜群。脂の乗った旬の魚を焼いたときの香ばしい匂いは食欲をそそる。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "nizakana", name: "煮魚", emoji: "🐟",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/nizakana.png",
    description: "醤油・みりん・砂糖で甘辛く煮付けた和食の定番おかず。かれい・ぶり・さばなどの魚を煮汁が染みるまでじっくり煮る。煮汁をご飯にかけて食べるのも美味しい食べ方のひとつ。シンプルな味付けながら魚の旨みが凝縮され、ご飯が進む和食の定番おかず。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "sashimi", name: "刺身", emoji: "🐠",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/sashimi.png",
    description: "新鮮な魚介をそのまま味わう。まぐろ・サーモン・鯛・いかなど旬の食材をシンプルに楽しめる一品。わさびと醤油で食べるのが定番だが、塩やポン酢でさっぱり食べる方法も人気。鮮度が命の料理なので、新鮮な魚介を選ぶことが最大のポイント。お酒のおつまみとしても最高の一品。",
    difficulty: 2, availability: 4,
    tags: ["ごちそう系", "おつまみ系"] },

  { id: "ebichili", name: "エビチリ", emoji: "🦐",
    type: "normal", category: ["fish"], genre: "chinese",
    image: "images/ebichili.png",
    description: "プリプリのエビをピリ辛チリソースで炒めた中華料理。豆板醤・ケチャップ・にんにく・生姜を合わせたチリソースが絶妙な味わい。エビの旨みとピリ辛ソースが絡み合い、ご飯が止まらなくなる。陳建民が日本向けにアレンジした料理として知られ、本場中国とは少し異なる日本独自の中華料理。",
    difficulty: 3, availability: 4,
    tags: ["辛い"] },

  { id: "ebimayo", name: "エビマヨ", emoji: "🦐",
    type: "normal", category: ["fish"], genre: "chinese",
    image: "images/ebimayo.png",
    description: "揚げたエビをマヨネーズソースで絡めたクリーミーな一品。プリプリに揚げたエビをマヨネーズ・ケチャップ・レモン汁を合わせたソースで和える。クリーミーなソースとエビの食感のコントラストが楽しい。中華料理店の人気メニューで、子どもから大人まで幅広く愛される定番おかず。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物"] },

  { id: "ajifry", name: "アジフライ", emoji: "🐟",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/ajifry.png",
    description: "サクサクの衣でアジを揚げた定食の定番。新鮮なアジを三枚におろしてパン粉をつけて揚げる。ソースをかけてそのまま食べるほか、タルタルソースを添えるスタイルも人気。アジの旨みとサクサクの衣の組み合わせが絶品で、定食屋の人気メニューとして長年愛されている。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物"] },

  { id: "ebifry", name: "エビフライ", emoji: "🦐",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/ebifry.png",
    description: "大きなエビをサクサクに揚げた洋食の定番。プリプリのエビに丁寧にパン粉をつけてきつね色に揚げる。タルタルソースとの相性が抜群で、洋食定食の主役として長年愛されている。尾の部分まで食べ尽くすのが通とされており、ボリューム感も魅力のひとつ。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物", "ごちそう系"] },

  { id: "kakifry", name: "カキフライ", emoji: "🦪",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/kakifry.png",
    description: "ジューシーな牡蠣をサクサクに揚げた秋冬の定番。濃厚な旨みが凝縮された牡蠣にパン粉をつけてこんがり揚げる。レモンを絞ってタルタルソースと一緒に食べるのが定番スタイル。牡蠣は「海のミルク」と呼ばれるほど栄養が豊富で、冬が旬の食材。揚げることで旨みが閉じ込められジューシーに仕上がる。",
    difficulty: 3, availability: 3,
    tags: ["揚げ物", "ごちそう系"] },

  { id: "buridaikon", name: "ぶり大根", emoji: "🐟",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/buridaikon.png",
    description: "ぶりと大根を甘辛く煮た冬の和食定番。脂の乗ったぶりと味が染みた大根の組み合わせが絶妙で、ご飯が進む煮物。生姜を加えることで魚の臭みが抑えられ、風味豊かに仕上がる。冬のぶりは特に脂が乗っていて美味しく、旬の味覚を楽しめる和食の定番おかず。",
    difficulty: 3, availability: 4,
    tags: [] },

  // ── 粉もの・チーズ系 ──────────────────────────
  { id: "okonomiyaki", name: "お好み焼き", emoji: "🥞",
    type: "normal", category: ["flour"], genre: "japanese",
    image: "images/okonomiyaki.png",
    description: "キャベツたっぷりの生地を焼いた粉もんの定番。広島風と大阪風でスタイルが大きく異なり、広島風は生地と具材を層にして焼き、大阪風は全部混ぜて焼く。マヨネーズ・ソース・青のり・かつお節のトッピングが定番。家族や友人とテーブルを囲んで焼きながら食べるのが楽しい。",
    difficulty: 3, availability: 4,
    tags: ["ジャンク系"] },

  { id: "takoyaki", name: "たこ焼き", emoji: "🐙",
    type: "normal", category: ["flour", "side"], genre: "japanese",
    image: "images/takoyaki.png",
    description: "外はカリッ、中はトロッとした大阪名物。専用のたこ焼き器でくるくると回しながら焼き上げる技術が必要で、熟練するほど美味しくなる。ソース・マヨネーズ・青のり・かつお節のトッピングが定番。大阪では「たこ焼きはおやつ」という文化があり、日常的に食べられている。",
    difficulty: 3, availability: 5,
    tags: ["ジャンク系", "おつまみ系"] },

  { id: "monjayaki", name: "もんじゃ焼き", emoji: "🥞",
    type: "normal", category: ["flour"], genre: "japanese",
    image: "images/monjayaki.png",
    description: "とろとろの生地をヘラで食べる東京下町の粉もん。薄い生地を鉄板に広げ、具材を堤防のように囲んでからスープを注いで焼く独特のスタイル。小さなヘラで鉄板に押し付けながら食べるのが定番で、最後のおこげが特に美味しい。東京の月島が有名な激戦区として知られている。",
    difficulty: 3, availability: 3,
    tags: [] },

  { id: "chijimi", name: "チヂミ", emoji: "🥞",
    type: "normal", category: ["flour"], genre: "other",
    image: "images/chijimi.png",
    description: "外はカリカリ、中はもちもちの韓国風お好み焼き。ニラ・ねぎ・えびなどを入れた生地を薄く伸ばしてカリカリに焼き上げる。コチュジャンや酢醤油のタレをつけて食べるのが定番。韓国では雨の日に食べる習慣があるとされており、ビールとの相性が抜群のおつまみ。",
    difficulty: 2, availability: 4,
    tags: ["おつまみ系"] },

  { id: "pizza", name: "ピザ", emoji: "🍕",
    type: "normal", category: ["flour"], genre: "western",
    image: "images/pizza.png",
    description: "トッピング次第で無限のアレンジが楽しめる人気料理。マルゲリータ・マリナーラなどイタリアの定番から、照り焼きチキンや明太子など日本独自のアレンジまで幅広い。モチモチのナポリ風からパリパリのローマ風まで生地のスタイルも多彩。宅配ピザは特別な日の定番で、みんなでシェアして食べるのが楽しい。",
    difficulty: 3, availability: 5,
    tags: ["ごちそう系", "ジャンク系"] },

  { id: "gratin", name: "グラタン", emoji: "🧀",
    type: "normal", category: ["flour"], genre: "western",
    image: "images/gratin.png",
    description: "とろとろのホワイトソースとチーズが絡むオーブン料理。マカロニ・鶏肉・玉ねぎなどをホワイトソースと合わせ、たっぷりのチーズをかけてオーブンで焼き上げる。表面のチーズが溶けてこんがり焼けた部分が特に美味しい。寒い季節に食べたくなる温かい洋食で、子どもから大人まで人気が高い。",
    difficulty: 4, availability: 4,
    tags: ["ごちそう系"] },

  { id: "takkaru", name: "チーズタッカルビ", emoji: "🧀",
    type: "heavy", category: ["flour"], genre: "other",
    image: "images/takkaru.png",
    description: "甘辛い鶏肉とチーズが絡み合う韓国の人気鍋料理。コチュジャンベースの甘辛いタレで鶏肉と野菜を炒め、とろとろに溶けたチーズに絡めて食べる。韓国のカフェや専門店で流行してから日本でも大人気に。チーズのまろやかさが辛さをちょうどよく中和し、やみつきになる味わい。",
    difficulty: 3, availability: 4,
    tags: ["辛い", "ごちそう系"] },

  // ── 鍋・汁物 ──────────────────────────────────
  { id: "yosenabe", name: "寄せ鍋", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "japanese",
    image: "images/yosenabe.png",
    description: "魚介・肉・野菜を何でも入れて煮る冬の定番鍋。昆布だしやかつおだしをベースにしたスープに、鶏肉・白菜・豆腐・ねぎ・きのこなどさまざまな具材を入れる。最後の雑炊やうどんで締めるのが定番スタイル。家族みんなで囲む温かい鍋は冬の食卓の主役。",
    difficulty: 2, availability: 4,
    tags: ["野菜多め", "ごちそう系"] },

  { id: "kimchinabe", name: "キムチ鍋", emoji: "🌶️",
    type: "heavy", category: ["nabe"], genre: "other",
    image: "images/kimchinabe.png",
    description: "キムチベースの辛旨スープが体を温める人気鍋。キムチの酸味と旨みが溶け出したスープに豚肉・豆腐・もやし・ニラなどを入れて煮込む。辛さの中に旨みが凝縮されており、寒い季節に食べると体の芯から温まる。締めにラーメンやご飯を入れるのが定番で、最後まで美味しく楽しめる。",
    difficulty: 2, availability: 4,
    tags: ["辛い", "野菜多め"] },

  { id: "tonyunabe", name: "豆乳鍋", emoji: "🍲",
    type: "normal", category: ["nabe"], genre: "japanese",
    image: "images/tonyunabe.png",
    description: "まろやかな豆乳スープが体に優しい鍋。豆乳と昆布だしを合わせたスープに白菜・きのこ・鶏肉・豆腐などを入れて煮込む。まろやかで優しい味わいが特徴で、胃腸に優しく体を温める。ポン酢やごまだれを添えて食べるのが定番。美容と健康を意識する人に人気の鍋料理。",
    difficulty: 2, availability: 4,
    tags: ["野菜多め"] },

  { id: "motsunabe", name: "もつ鍋", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "japanese",
    image: "images/motsunabe.png",
    description: "プリプリのもつとニラ・キャベツが絡む博多名物鍋。牛・豚のもつを醤油または味噌ベースのスープで煮込み、たっぷりのニラとキャベツを加える。コラーゲンたっぷりのもつが柔らかくなったころが食べごろ。締めにちゃんぽん麺を入れるのが博多スタイルで、お酒との相性も抜群。",
    difficulty: 3, availability: 3,
    tags: ["ごちそう系", "おつまみ系"] },

  { id: "mizutaki", name: "水炊き", emoji: "🍲",
    type: "normal", category: ["nabe"], genre: "japanese",
    image: "images/mizutaki.png",
    description: "澄んだスープで鶏肉と野菜をシンプルに楽しむ鍋。鶏骨からとった白濁スープに鶏もも肉・白菜・ねぎ・豆腐などを入れてシンプルに煮込む。ポン酢にもみじおろしを添えて食べるのが定番スタイル。博多の郷土料理として有名で、素材の旨みを最大限に引き出したやさしい味わいが特徴。",
    difficulty: 2, availability: 4,
    tags: ["野菜多め"] },

  { id: "chankonabe", name: "ちゃんこ鍋", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "japanese",
    image: "images/chankonabe.png",
    description: "肉・魚・野菜が豊富に入ったボリューム満点の力士鍋。鶏肉をベースにした醤油や塩ベースのスープに、野菜・豆腐・魚介などさまざまな具材を入れる。相撲部屋の食事として有名で、力士がたっぷり食べてスタミナをつけるための料理。具材が豊富で栄養バランスが良く、一般家庭でも人気が高い。",
    difficulty: 3, availability: 3,
    tags: ["ごちそう系", "野菜多め"] },

  { id: "shabu", name: "しゃぶしゃぶ", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "japanese",
    image: "images/shabu.png",
    description: "薄切り肉をさっとくぐらせてポン酢やごまだれで食べる鍋。昆布だしの鍋に薄切り牛肉や豚肉をさっとくぐらせて、好みのタレで食べるシンプルなスタイル。「しゃぶしゃぶ」という名前は肉を湯にくぐらせる動作の擬音語から。さっぱりと食べられるので野菜もたっぷり摂れる上品な鍋料理。",
    difficulty: 2, availability: 3,
    tags: ["ごちそう系"] },

  { id: "oden", name: "おでん", emoji: "🍢",
    type: "normal", category: ["nabe"], genre: "japanese",
    image: "images/oden.png",
    description: "だしが染みた大根・卵・練り物が嬉しい冬の定番。昆布・かつおだしのスープに大根・卵・こんにゃく・ちくわ・はんぺんなどを入れてじっくり煮込む。コンビニおでんが定着してから年中楽しめるようになった。からしをつけて食べるのが定番で、スープを飲み干すのも楽しみのひとつ。",
    difficulty: 3, availability: 5,
    tags: ["おつまみ系"] },

  { id: "tonjiru", name: "豚汁", emoji: "🍵",
    type: "normal", category: ["nabe", "side"], genre: "japanese",
    image: "images/tonjiru.png",
    description: "豚肉と根菜の旨みが溶け込んだ具だくさんの味噌汁。豚肉・大根・にんじん・ごぼう・こんにゃくなどの具材を炒めてから味噌で仕上げる。具材の旨みが溶け出したスープが絶品で、ご飯との相性は抜群。体が温まり腹持ちも良いので、寒い日の朝食や定食の一品として最適。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "stew", name: "シチュー", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "western",
    image: "images/stew.png",
    description: "クリームまたはデミグラスベースで野菜と肉を煮込んだ洋食鍋。鶏肉や牛肉にじゃがいも・にんじん・玉ねぎを加えてじっくり煮込む。クリームシチューはまろやかな白いスープ、ビーフシチューは濃厚なブラウンソースが特徴。パンと一緒に食べるのも人気で、寒い季節に体が温まる洋食の定番。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系", "野菜多め"] },

  { id: "soup", name: "スープ", emoji: "🍵",
    type: "light", category: ["nabe", "side"], genre: "western",
    image: "images/soup.png",
    description: "体の芯から温まる一杯。コンソメや野菜ベースのあっさりしたスープから、クリーミーなポタージュまでバリエーションが豊富。野菜・豆・肉などさまざまな具材でアレンジができる。食事の最初に飲むと消化が促進され、体を温めてくれる効果もある。軽い食事の日でも満足感を補ってくれる。",
    difficulty: 2, availability: 5,
    tags: [] },

  // ── 軽食・サイド ──────────────────────────────
  { id: "sandwich", name: "サンドイッチ", emoji: "🥪",
    type: "light", category: ["side"], genre: "western",
    image: "images/sandwich.png",
    description: "手軽に食べられるパン料理。ハム・チーズ・野菜・卵など好みの具材を挟むだけで完成する手軽さが魅力。朝食やランチにぴったりで、具材次第でボリューム満点にもヘルシーにもなる。コンビニやカフェの定番商品としても親しまれており、持ち運びしやすいのもポイント。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "hotdog", name: "ホットドッグ", emoji: "🌭",
    type: "light", category: ["side"], genre: "western",
    image: "images/hotdog.png",
    description: "ソーセージをパンに挟んだ手軽なファストフード。ジューシーなソーセージをふわふわのバンズに挟み、ケチャップとマスタードをかけるのが定番スタイル。アメリカ発祥のファストフードで、スポーツ観戦やイベントの定番フードとして世界中で親しまれている。手軽に食べられてボリュームも満足感も十分。",
    difficulty: 1, availability: 4,
    tags: ["ジャンク系"] },

  { id: "caprese", name: "カプレーゼ", emoji: "🍅",
    type: "light", category: ["side"], genre: "western",
    image: "images/caprese.png",
    description: "トマトとモッツァレラチーズをオリーブオイルで楽しむイタリアの定番サラダ。イタリア・カプリ島発祥のシンプルな料理で、赤・白・緑の配色がイタリア国旗を表している。新鮮なトマトとフレッシュモッツァレラに塩・オリーブオイル・バジルをかけるだけ。素材の質が味に直結するため、新鮮な食材を選ぶことが大切。",
    difficulty: 1, availability: 4,
    tags: ["おつまみ系"] },

  { id: "hiyayakko", name: "冷奴", emoji: "🫙",
    type: "light", category: ["side"], genre: "japanese",
    image: "images/hiyayakko.png",
    description: "冷たい豆腐に薬味をのせてさっぱり食べる夏の定番。絹ごし豆腐または木綿豆腐に、ねぎ・生姜・かつお節・醤油をかけるシンプルなスタイル。夏の暑い日に食欲がないときでもするっと食べられる。豆腐はたんぱく質が豊富でヘルシーなため、健康を意識する人にも人気の一品。",
    difficulty: 1, availability: 5,
    tags: ["おつまみ系"] },

  { id: "yogurt", name: "ヨーグルト", emoji: "🥛",
    type: "light", category: ["side"], genre: "western",
    image: "images/yogurt.png",
    description: "腸活にもなる手軽な一品。乳酸菌が豊富で腸内環境を整える効果があるとされており、毎日の習慣として取り入れる人も多い。プレーンタイプにはちみつやジャムを加えて食べるのが人気で、フルーツと合わせてもおいしい。朝食やデザートとして手軽に食べられ、ダイエット中のおやつとしても定番。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "cereal", name: "シリアル", emoji: "🥣",
    type: "light", category: ["side"], genre: "western",
    image: "images/cereal.png",
    description: "牛乳をかけるだけの手軽な朝食。コーンフレーク・グラノーラ・ミューズリーなどさまざまな種類があり、好みに合わせて選べる。牛乳の代わりに豆乳やヨーグルトをかけるアレンジも人気。忙しい朝でも手間なく食べられて、栄養バランスも取りやすい現代の定番朝食。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "fruits", name: "フルーツ", emoji: "🍎",
    type: "light", category: ["side"], genre: "other",
    image: "images/fruits.png",
    description: "自然の甘みとビタミンが嬉しい。旬のフルーツは栄養価が高く、ビタミンCや食物繊維が豊富。食後のデザートや朝食の一品として手軽に取り入れられる。季節ごとに旬のフルーツを楽しむことで、食卓に彩りと季節感が生まれる。甘みと酸味のバランスが食欲をリセットしてくれる。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "toast", name: "トースト", emoji: "🍞",
    type: "light", category: ["side"], genre: "western",
    image: "images/toast.png",
    description: "焼いたパンにバターやジャムを塗るだけの朝の定番。多くの家庭で親しまれているシンプルなメニューで、バター・ジャムの定番からアボカドトーストや明太子トーストなどアレンジも豊富。パンをこんがり焼いたときの香ばしい香りが食欲をそそる。手軽さと満足感を両立した朝食の定番。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "dashimaki", name: "だし巻き卵", emoji: "🥚",
    type: "light", category: ["side"], genre: "japanese",
    image: "images/dashimaki.png",
    description: "だしをたっぷり含んだふわふわの卵焼き。だし・醤油・みりんを合わせた卵液を巻きながら焼き上げる技術が必要な和食の定番。ふわふわの食感とだしの旨みが口の中に広がる。お弁当や定食の定番脇役として欠かせない存在で、大根おろしを添えて食べるのが定番スタイル。",
    difficulty: 3, availability: 5,
    tags: ["おつまみ系"] },

  { id: "bagel", name: "ベーグル", emoji: "🥯",
    type: "light", category: ["side"], genre: "western",
    image: "images/bagel.png",
    description: "もちもちした食感が特徴のパン。生地を一度茹でてからオーブンで焼くという独特の製法で、外はしっかり、中はもちもちに仕上がる。クリームチーズとスモークサーモンの組み合わせが定番で、さまざまな具材と相性が良い。低脂肪でボリューム感があり、健康志向の人にも人気のパン。",
    difficulty: 1, availability: 4,
    tags: [] },

  { id: "frenchfries", name: "フライドポテト", emoji: "🍟",
    type: "light", category: ["side"], genre: "western",
    image: "images/frenchfries.png",
    description: "サクサクに揚げたじゃがいも。じゃがいもを拍子木切りや薄切りにして揚げたシンプルなメニューで、塩だけでも十分な美味しさ。ケチャップやマヨネーズとの相性が抜群で、ハンバーガーやステーキの付け合わせとしても定番。ファストフードの定番として世界中で親しまれている。",
    difficulty: 2, availability: 5,
    tags: ["ジャンク系", "おつまみ系", "揚げ物"] },

  { id: "salad", name: "サラダ", emoji: "🥗",
    type: "light", category: ["side"], genre: "western",
    image: "images/salad.png",
    description: "野菜たっぷりでヘルシー。レタス・トマト・きゅうりなどの定番野菜から、アボカドやブロッコリーを加えたアレンジまで幅広い。ドレッシング次第で味が大きく変わるため、好みのドレッシングを見つける楽しみもある。食事のバランスを整えるためにも、毎食一品加えたいヘルシーなメニュー。",
    difficulty: 1, availability: 5,
    tags: ["野菜多め"] },

  { id: "hamburger", name: "ハンバーガー", emoji: "🍔",
    type: "normal", category: ["meat", "side"], genre: "western",
    image: "images/hamburger.png",
    description: "肉のパティに野菜とソースを挟んだ定番ハンバーガー。ジューシーなビーフパティにレタス・トマト・チーズ・ピクルスを重ね、バンズで挟む定番スタイル。ファストフードの代名詞として世界中で親しまれており、グルメバーガー専門店も増加中。ボリューム満点で食べ応えがあり、若い世代を中心に根強い人気。",
    difficulty: 3, availability: 5,
    tags: ["ジャンク系"] },

];