const meals = [

  // ── ご飯もの ──────────────────────────────
  { id: "curry", name: "カレー", emoji: "🍛",
    type: "heavy", category: ["rice"], genre: "japanese",
    image: "images/curry.png",
    description: "スパイスが効いた定番の人気メニュー。",
    difficulty: 3, availability: 5,
    tags: ["ごちそう系"] },

  { id: "hayashi", name: "ハヤシライス", emoji: "🍛",
    type: "heavy", category: ["rice"], genre: "western",
    image: "images/hayashi.png",
    description: "デミグラスソースで煮込んだ牛肉がご飯に合う洋食の定番。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系"] },

  { id: "gyudon", name: "牛丼", emoji: "🥣",
    type: "normal", category: ["rice", "meat"], genre: "japanese",
    image: "images/gyudon.png",
    description: "甘辛い牛肉がご飯に染みる、手軽でうまい丼。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "oyakodon", name: "親子丼", emoji: "🥚",
    type: "normal", category: ["rice", "meat"], genre: "japanese",
    image: "images/oyakodon.png",
    description: "鶏肉と卵のふわとろコンビが絶品。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "katsudon", name: "カツ丼", emoji: "🍱",
    type: "heavy", category: ["rice", "meat"], genre: "japanese",
    image: "images/katsudon.png",
    description: "サクサクのとんかつを卵でとじた、ボリューム満点の丼。",
    difficulty: 3, availability: 5,
    tags: ["ごちそう系", "揚げ物"] },

  { id: "chukadan", name: "中華丼", emoji: "🥡",
    type: "heavy", category: ["rice"], genre: "chinese",
    image: "images/chukadan.png",
    description: "八宝菜風のあんがご飯に絡む、ボリューム満点の中華丼。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "butadon", name: "豚丼", emoji: "🥣",
    type: "heavy", category: ["rice", "meat"], genre: "japanese",
    image: "images/butadon.png",
    description: "甘辛いタレで焼いた豚肉がご飯に乗った北海道名物。",
    difficulty: 2, availability: 5,
    tags: ["ごちそう系"] },

  { id: "omurice", name: "オムライス", emoji: "🍳",
    type: "normal", category: ["rice"], genre: "western",
    image: "images/omurice.png",
    description: "ケチャップライスをふわふわ卵で包んだ洋食の定番。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系"] },

  { id: "friedrice", name: "チャーハン", emoji: "🍚",
    type: "normal", category: ["rice"], genre: "chinese",
    image: "images/friedrice.png",
    description: "パラパラに炒めたご飯が香ばしい中華の定番。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "tenshinhan", name: "天津飯", emoji: "🍳",
    type: "normal", category: ["rice"], genre: "chinese",
    image: "images/tenshinhan.png",
    description: "ふわふわのかに玉あんかけがご飯に乗った中華の定番。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "doria", name: "ドリア", emoji: "🍚",
    type: "normal", category: ["rice", "flour"], genre: "western",
    image: "images/doria.png",
    description: "クリームソースとチーズをかけてオーブンで焼いた洋食。",
    difficulty: 4, availability: 3,
    tags: ["ごちそう系"] },

  { id: "bibimbap", name: "ビビンバ", emoji: "🥗",
    type: "normal", category: ["rice"], genre: "other",
    image: "images/bibimbap.png",
    description: "ナムルや肉を混ぜて食べる韓国の定番ご飯。",
    difficulty: 3, availability: 4,
    tags: ["辛い"] },

  { id: "tacorice", name: "タコライス", emoji: "🌮",
    type: "normal", category: ["rice"], genre: "other",
    image: "images/tacorice.png",
    description: "タコスの具材をご飯に乗せた沖縄発のB級グルメ。",
    difficulty: 2, availability: 4,
    tags: ["ジャンク系"] },

  { id: "loco", name: "ロコモコ丼", emoji: "🍳",
    type: "heavy", category: ["rice", "meat"], genre: "other",
    image: "images/loco.png",
    description: "ハンバーグと目玉焼きをグレービーソースで絡めたハワイ料理。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系"] },

  { id: "gapao", name: "ガパオライス", emoji: "🌿",
    type: "normal", category: ["rice"], genre: "other",
    image: "images/gapao.png",
    description: "バジルと鶏肉の炒め物を乗せたタイ料理。目玉焼き必須。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "kaisen", name: "海鮮丼", emoji: "🐟",
    type: "normal", category: ["rice", "fish"], genre: "japanese",
    image: "images/kaisen.png",
    description: "新鮮な魚介がたっぷり乗った贅沢な丼。",
    difficulty: 2, availability: 4,
    tags: ["ごちそう系"] },

  { id: "sushi", name: "寿司", emoji: "🍣",
    type: "heavy", category: ["rice", "fish"], genre: "japanese",
    image: "images/sushi.png",
    description: "新鮮なネタとシャリの組み合わせが最高。",
    difficulty: 4, availability: 4,
    tags: ["ごちそう系"] },

  { id: "unaju", name: "うな重", emoji: "🐡",
    type: "heavy", category: ["rice", "fish"], genre: "japanese",
    image: "images/unaju.png",
    description: "タレをたっぷり絡めた鰻がご飯に乗った特別感のある一品。",
    difficulty: 4, availability: 3,
    tags: ["ごちそう系"] },

  { id: "tkg", name: "卵かけご飯", emoji: "🥚",
    type: "light", category: ["rice", "side"], genre: "japanese",
    image: "images/tkg.png",
    description: "シンプルだけど奥深い、日本人のソウルフード。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "onigiri", name: "おにぎり", emoji: "🍙",
    type: "light", category: ["rice", "side"], genre: "japanese",
    image: "images/onigiri.png",
    description: "シンプルだけど飽きない日本の定番。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "ochazuke", name: "お茶漬け", emoji: "🍵",
    type: "light", category: ["rice", "side"], genre: "japanese",
    image: "images/ochazuke.png",
    description: "だし茶をかけてさらっと食べる和のファストフード。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "tendon", name: "天丼", emoji: "🍤",
    type: "heavy", category: ["rice"], genre: "japanese",
    image: "images/tendon.png",
    description: "サクサクの天ぷらにタレが絡む、ご飯が進む丼もの。",
    difficulty: 4, availability: 4,
    tags: ["ごちそう系", "揚げ物"] },

  // ── 麺類 ──────────────────────────────────
  { id: "ramen", name: "ラーメン", emoji: "🍜",
    type: "heavy", category: ["noodle"], genre: "chinese",
    image: "images/ramen.png",
    description: "濃厚なスープと麺が絡む、日本の国民食。",
    difficulty: 2, availability: 5,
    tags: ["ごちそう系"] },

  { id: "udon", name: "うどん", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "japanese",
    image: "images/udon.png",
    description: "もちもちの麺が体に優しい定番麺。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "soba", name: "そば", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "japanese",
    image: "images/soba.png",
    description: "風味豊かな蕎麦の香りがたまらない。さっぱり食べたい日に。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "hiyashi", name: "冷やし中華", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "chinese",
    image: "images/hiyashi.png",
    description: "暑い日に食べたくなる夏の定番麺。",
    difficulty: 2, availability: 4,
    tags: [] },

  { id: "tsukemen", name: "つけ麺", emoji: "🍜",
    type: "heavy", category: ["noodle"], genre: "chinese",
    image: "images/tsukemen.png",
    description: "濃厚なつけ汁に麺をくぐらせて食べる、ラーメンの進化系。",
    difficulty: 2, availability: 4,
    tags: ["ごちそう系"] },

  { id: "yakisoba", name: "焼きそば", emoji: "🍜",
    type: "normal", category: ["noodle"], genre: "japanese",
    image: "images/yakisoba.png",
    description: "ソース香る炒め麺。お祭りの屋台を思い出す味。",
    difficulty: 2, availability: 5,
    tags: ["ジャンク系"] },

  { id: "pasta", name: "パスタ", emoji: "🍝",
    type: "normal", category: ["noodle"], genre: "western",
    image: "images/pasta.png",
    description: "ソース次第で無限のアレンジが楽しめるイタリアの定番。",
    difficulty: 3, availability: 5,
    tags: [] },

  { id: "tantanmen", name: "担々麺", emoji: "🍜",
    type: "heavy", category: ["noodle"], genre: "chinese",
    image: "images/tantanmen.png",
    description: "ピリ辛のごまスープが濃厚でクセになる中華麺。",
    difficulty: 3, availability: 4,
    tags: ["辛い", "ごちそう系"] },

  { id: "chanpon", name: "ちゃんぽん", emoji: "🍜",
    type: "heavy", category: ["noodle"], genre: "chinese",
    image: "images/chanpon.png",
    description: "野菜・肉・魚介がたっぷり入った長崎発のボリューム麺。",
    difficulty: 3, availability: 4,
    tags: ["野菜多め"] },

  { id: "reimen", name: "冷麺", emoji: "🍜",
    type: "normal", category: ["noodle"], genre: "other",
    image: "images/reimen.png",
    description: "コシのある麺を冷たいスープで食べる韓国料理。",
    difficulty: 2, availability: 4,
    tags: ["辛い"] },

  { id: "somen", name: "素麺", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "japanese",
    image: "images/somen.png",
    description: "夏の暑い日にするっと食べられる細麺。冷やして食べるのが定番。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "pho", name: "フォー", emoji: "🍜",
    type: "light", category: ["noodle"], genre: "other",
    image: "images/pho.png",
    description: "澄んだスープと米粉麺が体に優しいベトナムの定番麺。",
    difficulty: 3, availability: 3,
    tags: [] },

  // ── 肉料理 ──────────────────────────────────
  { id: "yakiniku", name: "焼肉", emoji: "🥩",
    type: "heavy", category: ["meat"], genre: "other",
    image: "images/yakiniku.png",
    description: "自分で焼くのが楽しい、みんな大好きな肉料理。",
    difficulty: 2, availability: 2,
    tags: ["ごちそう系"] },

  { id: "steak", name: "ステーキ", emoji: "🥩",
    type: "heavy", category: ["meat"], genre: "western",
    image: "images/steak.png",
    description: "豪快に焼いた厚切り肉。特別感があってテンションが上がる。",
    difficulty: 3, availability: 3,
    tags: ["ごちそう系"] },

  { id: "hamburg", name: "ハンバーグ", emoji: "🍖",
    type: "heavy", category: ["meat"], genre: "western",
    image: "images/hamburg.png",
    description: "ジューシーな肉汁があふれる洋食の定番。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系"] },

  { id: "karaage", name: "唐揚げ", emoji: "🍗",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/karaage.png",
    description: "外はカリッ、中はジューシー。揚げ物の王様。",
    difficulty: 3, availability: 5,
    tags: ["揚げ物", "おつまみ系"] },

  { id: "tonkatsu", name: "とんかつ", emoji: "🍖",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/tonkatsu.png",
    description: "サクサクの衣に包まれたジューシーな豚肉。ご飯が進む。",
    difficulty: 3, availability: 5,
    tags: ["揚げ物", "ごちそう系"] },

  { id: "chickenkatsu", name: "チキンカツ", emoji: "🍗",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/chickenkatsu.png",
    description: "鶏肉をサクサクに揚げたカツ。とんかつより軽めで食べやすい。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物"] },

  { id: "chikinnamban", name: "チキン南蛮", emoji: "🍗",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/chikinnamban.png",
    description: "甘酢とタルタルソースが絡む宮崎発の鶏肉料理。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物", "ごちそう系"] },

  { id: "yurinchi", name: "油淋鶏", emoji: "🍗",
    type: "heavy", category: ["meat"], genre: "chinese",
    image: "images/yurinchi.png",
    description: "揚げた鶏肉にネギソースをかけた中華料理。ご飯が進む。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物"] },

  { id: "shogayaki", name: "豚の生姜焼き", emoji: "🥩",
    type: "normal", category: ["meat"], genre: "japanese",
    image: "images/shogayaki.png",
    description: "甘辛い生姜ダレで炒めた豚肉。定食の王道。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "yakitori", name: "焼き鳥", emoji: "🍢",
    type: "normal", category: ["meat"], genre: "japanese",
    image: "images/yakitori.png",
    description: "タレや塩でシンプルに焼いた鶏肉串。お酒にもご飯にも合う。",
    difficulty: 3, availability: 5,
    tags: ["おつまみ系"] },

  { id: "roastbeef", name: "ローストビーフ", emoji: "🥩",
    type: "heavy", category: ["meat"], genre: "western",
    image: "images/roastbeef.png",
    description: "じっくり焼いた牛肉の塊。おもてなしにぴったりな特別料理。",
    difficulty: 4, availability: 3,
    tags: ["ごちそう系"] },

  { id: "hoikoro", name: "回鍋肉", emoji: "🥬",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/hoikoro.png",
    description: "キャベツと豚肉を甜麺醤で炒めた中華の定番おかず。",
    difficulty: 3, availability: 4,
    tags: ["野菜多め"] },

  { id: "subuta", name: "酢豚", emoji: "🍖",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/subuta.png",
    description: "揚げた豚肉を甘酢あんで絡めた中華の人気料理。",
    difficulty: 4, availability: 4,
    tags: ["揚げ物"] },

  { id: "chinjao", name: "青椒肉絲", emoji: "🫑",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/chinjao.png",
    description: "ピーマンと牛肉の細切り炒め。シンプルな中華おかず。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "mapo", name: "麻婆豆腐", emoji: "🌶️",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/mapo.png",
    description: "ピリ辛のひき肉あんが豆腐に絡む中華の定番。",
    difficulty: 3, availability: 5,
    tags: ["辛い"] },

  { id: "rebanira", name: "レバニラ炒め", emoji: "🥬",
    type: "normal", category: ["meat"], genre: "chinese",
    image: "images/rebanira.png",
    description: "レバーとニラを炒めたスタミナ満点の中華おかず。",
    difficulty: 2, availability: 4,
    tags: [] },

  { id: "gyoza", name: "餃子", emoji: "🥟",
    type: "normal", category: ["meat", "side"], genre: "chinese",
    image: "images/gyoza.png",
    description: "パリッと焼けた皮とジューシーな餡が最高。",
    difficulty: 3, availability: 5,
    tags: ["おつまみ系"] },

  { id: "kakuni", name: "豚の角煮", emoji: "🍖",
    type: "heavy", category: ["meat"], genre: "japanese",
    image: "images/kakuni.png",
    description: "じっくり煮込んだ豚バラ肉がとろとろに仕上がる。",
    difficulty: 4, availability: 4,
    tags: ["ごちそう系"] },

  { id: "nikujaga", name: "肉じゃが", emoji: "🥔",
    type: "normal", category: ["meat"], genre: "japanese",
    image: "images/nikujaga.png",
    description: "じゃがいもと肉を甘辛く煮た和食の定番おかず。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "rollcabbage", name: "ロールキャベツ", emoji: "🥬",
    type: "normal", category: ["meat"], genre: "western",
    image: "images/rollcabbage.png",
    description: "キャベツでひき肉を包んでじっくり煮込んだ洋食おかず。",
    difficulty: 4, availability: 4,
    tags: ["野菜多め"] },

  { id: "croquette", name: "コロッケ", emoji: "🥔",
    type: "normal", category: ["meat", "side"], genre: "japanese",
    image: "images/croquette.png",
    description: "じゃがいもとひき肉をサクサクに揚げた定番惣菜。",
    difficulty: 3, availability: 5,
    tags: ["揚げ物"] },

  { id: "menchikatsu", name: "メンチカツ", emoji: "🍖",
    type: "normal", category: ["meat", "side"], genre: "japanese",
    image: "images/menchikatsu.png",
    description: "ひき肉をサクサクの衣で揚げたボリューム感のある惣菜。",
    difficulty: 3, availability: 5,
    tags: ["揚げ物"] },

  { id: "sukiyaki", name: "すき焼き", emoji: "🍲",
    type: "heavy", category: ["meat", "nabe"], genre: "japanese",
    image: "images/sukiyaki.png",
    description: "甘辛いタレで牛肉や野菜を煮た日本の特別なごちそう鍋。",
    difficulty: 3, availability: 3,
    tags: ["ごちそう系"] },

  // ── 魚料理 ──────────────────────────────────
  { id: "yakizakana", name: "焼魚", emoji: "🐟",
    type: "light", category: ["fish"], genre: "japanese",
    image: "images/yakizakana.png",
    description: "塩焼きや醤油焼きでシンプルに。和食の朝ごはんにも定番。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "nizakana", name: "煮魚", emoji: "🐟",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/nizakana.png",
    description: "醤油・みりん・砂糖で甘辛く煮付けた和食の定番おかず。",
    difficulty: 3, availability: 4,
    tags: [] },

  { id: "sashimi", name: "刺身", emoji: "🐠",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/sashimi.png",
    description: "新鮮な魚介をそのまま味わう。シンプルゆえに素材が主役。",
    difficulty: 2, availability: 4,
    tags: ["ごちそう系", "おつまみ系"] },

  { id: "ebichili", name: "エビチリ", emoji: "🦐",
    type: "normal", category: ["fish"], genre: "chinese",
    image: "images/ebichili.png",
    description: "プリプリのエビをピリ辛チリソースで炒めた中華料理。",
    difficulty: 3, availability: 4,
    tags: ["辛い"] },

  { id: "ebimayo", name: "エビマヨ", emoji: "🦐",
    type: "normal", category: ["fish"], genre: "chinese",
    image: "images/ebimayo.png",
    description: "揚げたエビをマヨネーズソースで絡めたクリーミーな一品。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物"] },

  { id: "ajifry", name: "アジフライ", emoji: "🐟",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/ajifry.png",
    description: "サクサクの衣でアジを揚げた定食の定番。ソースをかけて。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物"] },

  { id: "ebifry", name: "エビフライ", emoji: "🦐",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/ebifry.png",
    description: "大きなエビをサクサクに揚げた洋食の定番。",
    difficulty: 3, availability: 4,
    tags: ["揚げ物", "ごちそう系"] },

  { id: "kakifry", name: "カキフライ", emoji: "🦪",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/kakifry.png",
    description: "ジューシーな牡蠣をサクサクに揚げた秋冬の定番。",
    difficulty: 3, availability: 3,
    tags: ["揚げ物", "ごちそう系"] },

  { id: "buridaikon", name: "ぶり大根", emoji: "🐟",
    type: "normal", category: ["fish"], genre: "japanese",
    image: "images/buridaikon.png",
    description: "ぶりと大根を甘辛く煮た冬の和食定番。ご飯がすすむ。",
    difficulty: 3, availability: 4,
    tags: [] },

  // ── 粉もの・チーズ系 ──────────────────────────
  { id: "okonomiyaki", name: "お好み焼き", emoji: "🥞",
    type: "normal", category: ["flour"], genre: "japanese",
    image: "images/okonomiyaki.png",
    description: "キャベツたっぷりの生地を焼いた粉もんの定番。",
    difficulty: 3, availability: 4,
    tags: ["ジャンク系"] },

  { id: "takoyaki", name: "たこ焼き", emoji: "🐙",
    type: "normal", category: ["flour", "side"], genre: "japanese",
    image: "images/takoyaki.png",
    description: "外はカリッ、中はトロッとした大阪名物。",
    difficulty: 3, availability: 5,
    tags: ["ジャンク系", "おつまみ系"] },

  { id: "monjayaki", name: "もんじゃ焼き", emoji: "🥞",
    type: "normal", category: ["flour"], genre: "japanese",
    image: "images/monjayaki.png",
    description: "とろとろの生地をヘラで食べる東京下町の粉もん。",
    difficulty: 3, availability: 3,
    tags: [] },

  { id: "chijimi", name: "チヂミ", emoji: "🥞",
    type: "normal", category: ["flour"], genre: "other",
    image: "images/chijimi.png",
    description: "外はカリカリ、中はもちもちの韓国風お好み焼き。",
    difficulty: 2, availability: 4,
    tags: ["おつまみ系"] },

  { id: "pizza", name: "ピザ", emoji: "🍕",
    type: "normal", category: ["flour"], genre: "western",
    image: "images/pizza.png",
    description: "トッピング次第で無限のアレンジが楽しめる人気料理。",
    difficulty: 3, availability: 5,
    tags: ["ごちそう系", "ジャンク系"] },

  { id: "gratin", name: "グラタン", emoji: "🧀",
    type: "normal", category: ["flour"], genre: "western",
    image: "images/gratin.png",
    description: "とろとろのホワイトソースとチーズが絡むオーブン料理。",
    difficulty: 4, availability: 4,
    tags: ["ごちそう系"] },

  { id: "takkaru", name: "チーズタッカルビ", emoji: "🧀",
    type: "heavy", category: ["flour"], genre: "other",
    image: "images/takkaru.png",
    description: "甘辛い鶏肉とチーズが絡み合う韓国の人気鍋料理。",
    difficulty: 3, availability: 4,
    tags: ["辛い", "ごちそう系"] },

  // ── 鍋・汁物 ──────────────────────────────────
  { id: "yosenabe", name: "寄せ鍋", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "japanese",
    image: "images/yosenabe.png",
    description: "魚介・肉・野菜を何でも入れて煮る冬の定番鍋。",
    difficulty: 2, availability: 4,
    tags: ["野菜多め", "ごちそう系"] },

  { id: "kimchinabe", name: "キムチ鍋", emoji: "🌶️",
    type: "heavy", category: ["nabe"], genre: "other",
    image: "images/kimchinabe.png",
    description: "キムチベースの辛旨スープが体を温める人気鍋。",
    difficulty: 2, availability: 4,
    tags: ["辛い", "野菜多め"] },

  { id: "tonyunabe", name: "豆乳鍋", emoji: "🍲",
    type: "normal", category: ["nabe"], genre: "japanese",
    image: "images/tonyunabe.png",
    description: "まろやかな豆乳スープが体に優しい鍋。野菜たっぷり。",
    difficulty: 2, availability: 4,
    tags: ["野菜多め"] },

  { id: "motsunabe", name: "もつ鍋", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "japanese",
    image: "images/motsunabe.png",
    description: "プリプリのもつとニラ・キャベツが絡む博多名物鍋。",
    difficulty: 3, availability: 3,
    tags: ["ごちそう系", "おつまみ系"] },

  { id: "mizutaki", name: "水炊き", emoji: "🍲",
    type: "normal", category: ["nabe"], genre: "japanese",
    image: "images/mizutaki.png",
    description: "澄んだスープで鶏肉と野菜をシンプルに楽しむ鍋。",
    difficulty: 2, availability: 4,
    tags: ["野菜多め"] },

  { id: "chankonabe", name: "ちゃんこ鍋", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "japanese",
    image: "images/chankonabe.png",
    description: "肉・魚・野菜が豊富に入ったボリューム満点の力士鍋。",
    difficulty: 3, availability: 3,
    tags: ["ごちそう系", "野菜多め"] },

  { id: "shabu", name: "しゃぶしゃぶ", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "japanese",
    image: "images/shabu.png",
    description: "薄切り肉をさっとくぐらせてポン酢やごまだれで食べる鍋。",
    difficulty: 2, availability: 3,
    tags: ["ごちそう系"] },

  { id: "oden", name: "おでん", emoji: "🍢",
    type: "normal", category: ["nabe"], genre: "japanese",
    image: "images/oden.png",
    description: "だしが染みた大根・卵・練り物が嬉しい冬の定番。",
    difficulty: 3, availability: 5,
    tags: ["おつまみ系"] },

  { id: "tonjiru", name: "豚汁", emoji: "🍵",
    type: "normal", category: ["nabe", "side"], genre: "japanese",
    image: "images/tonjiru.png",
    description: "豚肉と根菜の旨みが溶け込んだ具だくさんの味噌汁。",
    difficulty: 2, availability: 5,
    tags: [] },

  { id: "stew", name: "シチュー", emoji: "🍲",
    type: "heavy", category: ["nabe"], genre: "western",
    image: "images/stew.png",
    description: "クリームまたはデミグラスベースで野菜と肉を煮込んだ洋食鍋。",
    difficulty: 3, availability: 4,
    tags: ["ごちそう系", "野菜多め"] },

  { id: "soup", name: "スープ", emoji: "🍵",
    type: "light", category: ["nabe", "side"], genre: "western",
    image: "images/soup.png",
    description: "体の芯から温まる一杯。コンソメや野菜ベースでさっぱり。",
    difficulty: 2, availability: 5,
    tags: [] },

  // ── 軽食・サイド ──────────────────────────────
  { id: "sandwich", name: "サンドイッチ", emoji: "🥪",
    type: "light", category: ["side"], genre: "western",
    image: "images/sandwich.png",
    description: "手軽に食べられるパン料理。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "hotdog", name: "ホットドッグ", emoji: "🌭",
    type: "light", category: ["side"], genre: "western",
    image: "images/hotdog.png",
    description: "ソーセージをパンに挟んだ手軽なファストフード。",
    difficulty: 1, availability: 4,
    tags: ["ジャンク系"] },

  { id: "caprese", name: "カプレーゼ", emoji: "🍅",
    type: "light", category: ["side"], genre: "western",
    image: "images/caprese.png",
    description: "トマトとモッツァレラチーズをオリーブオイルで。シンプルな美味しさ。",
    difficulty: 1, availability: 4,
    tags: ["おつまみ系"] },

  { id: "hiyayakko", name: "冷奴", emoji: "🫙",
    type: "light", category: ["side"], genre: "japanese",
    image: "images/hiyayakko.png",
    description: "冷たい豆腐に薬味をのせてさっぱり食べる夏の定番。",
    difficulty: 1, availability: 5,
    tags: ["おつまみ系"] },

  { id: "yogurt", name: "ヨーグルト", emoji: "🥛",
    type: "light", category: ["side"], genre: "western",
    image: "images/yogurt.png",
    description: "腸活にもなる手軽な一品。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "cereal", name: "シリアル", emoji: "🥣",
    type: "light", category: ["side"], genre: "western",
    image: "images/cereal.png",
    description: "牛乳をかけるだけの手軽な朝食。栄養バランスも取れる。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "fruits", name: "フルーツ", emoji: "🍎",
    type: "light", category: ["side"], genre: "other",
    image: "images/fruits.png",
    description: "自然の甘みとビタミンが嬉しい。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "toast", name: "トースト", emoji: "🍞",
    type: "light", category: ["side"], genre: "western",
    image: "images/toast.png",
    description: "焼いたパンにバターやジャムを塗るだけ。朝の定番。",
    difficulty: 1, availability: 5,
    tags: [] },

  { id: "dashimaki", name: "だし巻き卵", emoji: "🥚",
    type: "light", category: ["side"], genre: "japanese",
    image: "images/dashimaki.png",
    description: "だしをたっぷり含んだふわふわの卵焼き。和食の名脇役。",
    difficulty: 3, availability: 5,
    tags: ["おつまみ系"] },

  { id: "bagel", name: "ベーグル", emoji: "🥯",
    type: "light", category: ["side"], genre: "western",
    image: "images/bagel.png",
    description: "もちもちした食感が特徴のパン。クリームチーズとの相性抜群。",
    difficulty: 1, availability: 4,
    tags: [] },

  { id: "frenchfries", name: "フライドポテト", emoji: "🍟",
    type: "light", category: ["side"], genre: "western",
    image: "images/frenchfries.png",
    description: "サクサクに揚げたじゃがいも。何本でも食べてしまう。",
    difficulty: 2, availability: 5,
    tags: ["ジャンク系", "おつまみ系", "揚げ物"] },

  { id: "salad", name: "サラダ", emoji: "🥗",
    type: "light", category: ["side"], genre: "western",
    image: "images/salad.png",
    description: "野菜たっぷりでヘルシー。",
    difficulty: 1, availability: 5,
    tags: ["野菜多め"] },

  { id: "hamburger", name: "ハンバーガー", emoji: "🍔",
    type: "normal", category:  ["meat", "side"], genre: "western",
    image: "images/hamburger.png",
    description: "肉のパティに野菜とソースを挟んだ定番ハンバーガー。",
    difficulty: 3, availability: 5,
    tags: ["ジャンク系"] },

];
